name: Price checker cronjob

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python -m monitor.main
        env:
          PRODUCTS: ${{ secrets.PRODUCTS }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}

      - name: Save changed prices.csv file
        run: |
          if [[ `git diff --exit-code prices.csv` ]]; then
            git config --global user.name "Github Actions"
            git config --global user.email ""
            git add prices.csv
            git commit -m "[Cron] - Update prices.csv"
            git push
          else
            echo "No changes to 'prices.csv', skipping commit!"
          fi
        shell: bash